[package]
name = "conv"
version = "0.1.0"
authors = ["Jonir Rings <peterpuyi@live.cn>"]

[dependencies]
shellexpand = "1.0"
rust-crypto = "0.2.36"

[lib]
name = "conv_lib"
path = "src/lib.rs"

[[bin]]
name = "conv_bin"
path = "src/bin.rs"